---
 - copy:
     src: "{{ playbook_dir }}/pnda.tar"
     dest: "/home/{{ ansible_user }}/"
 - name: extract tar file
   unarchive:
     src: "/home/{{ ansible_user }}/pnda.tar"
     dest: "/home/{{ ansible_user }}/"
     remote_src: yes
 - name: create mirror
   shell: chdir="/home/{{ ansible_user }}/pnda/mirror" ./create_mirror.sh
   register: mirror
   async: 3600
   poll: 100
 - debug: var=mirror.stdout_lines
 - name: Getting hostname
   command: hostname
   register: hostname

 - name: adding private ip in /etc/hosts file
   lineinfile:
     path: /etc/hosts
     line: "127.0.1.1 {{ hostname.stdout }}"
     insertafter: EOF
 - name: install build tools
   shell: chdir="/home/{{ ansible_user }}/pnda/build" ./install-build-tools.sh
   register: tools
 - debug: var=tools.stdout_lines
 - name: build pnda
   shell: chdir="/home/{{ ansible_user }}/pnda/build" source set-pnda-env.sh && ./build-pnda.sh {{ tag }} {{ value }}
   register: build
   args:
     executable: /bin/bash
   async: 3600
   poll: 100
 - debug: var=build.stdout_lines
